### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by lisannevvliet** [lisannevvliet/erics-spraakassistent#11]
- [ ] Wachttijd na spraakcommando's vermelden (en eventueel instructies verbeteren).
- [ ] Geselecteerde tekst overschrijven.
- [ ] Optioneel: Checkbox maken om geselecteerde tekst automatisch te kopiëren.
- [ ] Optioneel: Spraakcommando's "kopieer geselecteerde tekst" en "selecteer" niet laten botsen. Spraakcommando's fail-proofen (optioneel).
- [ ] Index van resultaat op het juiste moment nul zetten, er kwam namelijk een bug voor waarbij meteen het tweede resultaat geselecteerd werd.
- [ ] Optioneel: Engelstalige spraakassistent ondersteunen.
- [ ] Optioneel: "Volgende" en "vorige" bij "selecteren vanaf ... tot ..." efficiënter maken.
- [ ] Optioneel: Stemcommando met [vertaaloptie](https://yandex.com/dev/translate/) implementeren.

- [ ] README.md bijwerken.
    - [ ] Beschrijven wat ik met zijn feedback heb gedaan.

- [ ] Test 3 afnemen.
    - [ ] Wat vind hij van de opnemen knop?
